### ISSUE TITLE
[Bug][InnoDB] Setting up InnoDB cluster as Devlake DB

### ISSUE THREAD

**Issue by pratiyush05** [apache/devlake#6451]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

Hi all , we tried configuring InnoDB cluster as Devlake DB. Met with an issue , few tables dont have primary keys in them . Group Replication has a requirement to have primary key in them .

Error shown - 
```
ERROR: The following tables do not have a Primary Key or equivalent column: 
lake._devlake_locking_stub, lake._tool_teambition_connections, lake._tool_bitbucket_pipeline_steps

Group Replication requires tables to use InnoDB and have a PRIMARY KEY or PRIMARY KEY Equivalent (non-null unique key). Tables that do not follow these requirements will be readable but not updateable when used with Group Replication. If your applications make updates (INSERT, UPDATE or DELETE) to these tables, ensure they use the InnoDB storage engine and have a PRIMARY KEY or PRIMARY KEY Equivalent.
If you can't change the tables structure to include an extra visible key to be used as PRIMARY KEY, you can make use of the INVISIBLE COLUMN feature available since 8.0.23: https://dev.mysql.com/doc/refman/8.0/en/invisible-columns.html

Checking instance configuration...

{
    "status": "error"
}
```

### What do you expect to happen

InnoDB cluster should have recognised devlake mysql instances .

### How to reproduce

1. Deploy devlake with a single mysql instance.
2. Deploy mysql-operator using helm-chart. ([link](https://dev.mysql.com/doc/mysql-operator/en/mysql-operator-installation-helm.html))
3. Deploy InnoDB cluster using helm-chart. ([link](https://dev.mysql.com/doc/mysql-operator/en/mysql-operator-innodbcluster-simple-helm.html))
4. Try validating mysql instance of step-1 for innodb cluster .(Used - dba.checkInstanceConfiguration('Mysql instance'))

### Anything else

We can bypass this issue by adding primary key to these tables for now .But it may culminate to become bigger problem when all datas are there on devlake and we try to upgrade Devlake to a higher version .

### Version

v0.19.0-beta2

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by d4x1** [comment]
@pratiyush05  Confirmed, it's a bug, I'm working on it, and it will be fix in v0.20.0-beta*.

**Comment by d4x1** [comment]
@pratiyush05 I have fixed missing primary keys in these table. Can you tell me your operations? When you meet this problem(bootstrap devlake or scale your database)?

**Comment by pratiyush05** [comment]
Hi @d4x1 , we met this when we were trying to set up devlake with InnoDB cluster as its DB for the first time. Group Replication property of InnoDB cluster needs Primary Keys for its functioning . 
We faced these compatibility issue -
1. We tried to include mysql instance to InnoDB cluster . Mysql Inst. was already having tables and old datas .Group replication was failing on it .
2. We later tried to first deploy InnoDB and then allow Devlake to create its tables . In this case , devlake couldnot create few of its tables ( cicd_deployment_commits table among few others ).

**Comment by d4x1** [comment]
@pratiyush05  situation 2,`cicd_deployment_commits` has primary keys, so it should be created successfully theretically.
Can you paste some useful logs to help us to debug this issue?

I am afraid my fix cannot work if devlake cannot init its tables in innodb cluster, but my fix should works on situation 1.

**Comment by pratiyush05** [comment]
@d4x1 
I re-preformed step 2 . I dont see any warning or error while performing it .
Steps -
1. Installed mysql innodb along with mysql operator .
2. Install devlake v0.19.0-beta2 with innodb service .

I captured few logs -
Migration started on install devlake in lake container -
<img width="1029" alt="Screenshot 2023-11-24 at 12 05 06 PM" src="https://github.com/apache/incubator-devlake/assets/110039059/0dabdaab-1547-4035-9963-4e7aa39a3c92">

After completion , found few domain layer tables missing -
<img width="545" alt="Screenshot 2023-11-24 at 12 08 21 PM" src="https://github.com/apache/incubator-devlake/assets/110039059/a712f239-6ab3-4b71-bb2b-25df084878c7">

**Comment by d4x1** [comment]
@pratiyush05  db migration is triggered in Config UI, have you triggered it manually? (just to make sure.)

**Comment by d4x1** [comment]
@pratiyush05  ok.
I test it with a new inno db database(not a cluster), and all tables are inited without trigger manually. 
And I think there is something wrong with you db cluster.  Does devlake connect to the master instance(read and write)?

**Comment by pratiyush05** [comment]
Yes Devlake connects with InnoDB cluster via its primary instance but it cannot write all tables and remains stuck in migration indefinitely .

**Comment by abeizn** [comment]
@pratiyush05 Can you share the status or screenshot of the config-ui?

**Comment by pratiyush05** [comment]
Sure ,
Status -
```
status:
  phase: Running
  conditions:
    - type: Initialized
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2023-11-24T09:22:06Z'
    - type: Ready
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2023-11-24T09:22:13Z'
    - type: ContainersReady
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2023-11-24T09:22:13Z'
    - type: PodScheduled
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2023-11-24T09:22:06Z'
  hostIP: X.X.X.X
  podIP: X.X.X.X
  podIPs:
    - ip: X.X.X.X
  startTime: '2023-11-24T09:22:06Z'
  containerStatuses:
    - name: config-ui
      state:
        running:
          startedAt: '2023-11-24T09:22:13Z'
      lastState: {}
      ready: true
      restartCount: 0
      image: devlake.docker.scarf.sh/apache/devlake-config-ui:v0.19.0-beta2
      imageID: >-
        docker-pullable://devlake.docker.scarf.sh/apache/devlake-config-ui@sha256:15fb0426d0a81c8c69e1852241449b8279d8e138323ff7085baf0dd9bf4ee161
      containerID: >-
        docker://e4c0861ff29a5acb4f3a4d85c339e044d61c7ea56787a90d0a2dd1565b843745
      started: true
  qosClass: BestEffort
```

Screenshot of config-ui -
<img width="720" alt="Screenshot 2023-11-24 at 2 53 01 PM" src="https://github.com/apache/incubator-devlake/assets/110039059/6cc0e036-9d08-4d33-ab9c-a6c38cec9fac">
