### ISSUE TITLE
[Question][HELM Chart] Not able to deploy via Traefik in Kubernetes

### ISSUE THREAD

**Issue by ChintanPania** [apache/devlake#6528]
## Question
Is there any specific configurations to be done when deploying the HELM using Traefik Ingress class in Kubernetes ?

## Screenshots
If applicable, add screenshots to help explain.

## Additional context
I use v0.19.0-beta6

I get 504 Gateway Timeout with the below configuration, UI Pod is running fine and I get HTML document when I exec curl inside the pod, there seems to be an issue between Ingress and Service.

Could someone please assist here ?

Below is my ingress configuration,

```
ingress:
  enabled: true
  enableHttps: false
  # Set to false if you want to use a different ingress controller
  useDefaultNginx: false
  # ingress class name, example: alb for AWS load balancer controller
  className: 
    # domain name for hosting devlake, must be set if ingress is enabled
  hostname: mydomain.com
  # annotations required for your ingress controller; see the examples below
  # for nginx, use the first two lines of annotations
  # for alb (w/ external-dns), use the last 5 (6) lines of annotations
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.tls: "true"
    # {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
    #
    # alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    # alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-2:xxx:certificate/xxx-xxx-xxx
    # alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}, {"HTTP":80}]'
    # alb.ingress.kubernetes.io/scheme: internet-facing
    # alb.ingress.kubernetes.io/target-type: ip
    # external-dns.alpha.kubernetes.io/hostname: www.example.com

  # url prefix, not works right now, keep "/"
  prefix: /
  # if using https provides the certificates secret name
  tlsSecretName: ""
  # ingress http port
  httpPort: 80
  # ingress https port
  httpsPort: 443
```
