### ISSUE TITLE
[Feature][docker compose] database client to explore data import

### ISSUE THREAD

**Issue by clement-igonet** [apache/devlake#6575]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Use case

* As a application installer
* I'd like to be able to easily explore DevLake DB
* In order to check data import

### Description

This could just be this docker service in `docker-compose.yml` file:
```
  adminer:
    image: adminer
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: mysql
    ports:
      - 8087:8080
 ```

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)
