### ISSUE TITLE
CircleCI Data not capture in DORA matrix in 0.21.beta3 version 

### ISSUE THREAD

**Issue by skanthekar** [apache/devlake#7073]
## Question
While adding CircleCI data connection in DevLake to collect Data for DORA matrix. 
I can not see analysis data from CircleCI CICD jobs.

Scenario that i expected. Please correct me if i assume anything wrong.
1. When i add data connection for CircleCI it shoud collect data from existing CICD jobs and represent using DORA matrix. But its not  working at current movement

Is any one guide me for CircleCI and Devlake integration ?
 
## Screenshots
If applicable, add screenshots to help explain.

## Additional context
Add any other context here.

**Comment by klesh** [comment]
I think the steps should be like:

1. Add CircleCI connection
2. Add CircleCI data scope under the connection
3. Setup the Scope Config properly
4. Add connection and data scope to the Project
5. Execute the project
6. See dashboard

**Comment by skanthekar** [comment]
Hi @klesh 

I tried steps mentioned by you. but it's not working for me
Please find below screen shots for more information

<img width="791" alt="image" src="https://github.com/apache/incubator-devlake/assets/138678524/317779ba-9e27-47d3-b6f6-a817fb0bf235">

<img width="688" alt="image" src="https://github.com/apache/incubator-devlake/assets/138678524/e266870c-9d8e-437c-8454-2f41382cb278">

Please guide me

**Comment by klesh** [comment]
How does your pipeline data look like? Share some sample?

**Comment by skanthekar** [comment]
Its simple pipeline that i have created for testing. Build and Deploy. using echo message

**Comment by klesh** [comment]
@skanthekar I don't know how to help with the information at hand. 😂

**Comment by lashkinaziy** [comment]
Hi @klesh. I ran into the same issue with 1.0.0-beta6. Using the CircleCI config below and setting the name to `build-stuff` is seen as deployment by DevLake. Setting the name to `deploy` is not seen as deployment. DevLake seems to be matching on workflow name only and ignoring the job name.

```yaml
version: 2.1
jobs:
    build-image:
      docker:
        - image: "cimg/base:stable"
      steps:
        - run:
            name: "building-image"
            command: |
              echo "We are pretending to build an image!"
              sleep 15
              echo "pipeline.id is << pipeline.id >>"
              echo "pipeline.number is << pipeline.number >>"
              
    deploy:
      docker:
        - image: "cimg/base:stable"
      steps:
        - run:
            name: "update-chart-of-helm"
            command: |
                echo "We are pretending to update Helm chart!"
                sleep 15
                echo "Done!!"
              
workflows:
  build-stuff:
    jobs:
      - build-image:
          name: build

      - deploy:
            name: deploy
            requires:
                - build
```
