### ISSUE TITLE
[Question] Ingress with subpath possible?

### ISSUE THREAD

**Issue by thiDucTran** [apache/devlake#7286]
Hi, I deployed using chart `1.0.0-beta3` . I am trying to create an Ingress like below, I keep getting 304 error. Is having an ingress with `path` like `/devlake` possible?

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/auth-signin: https://dev.myhost.io/oauth2/start?rd=$escaped_request_uri
    nginx.ingress.kubernetes.io/auth-url: https://dev.myhost.io/oauth2/auth
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  name: apache-devlake-ingress
  namespace: infra
spec:
  ingressClassName: nginx
  rules:
  - host: dev.myhost.io
    http:
      paths:
      - backend:
          service:
            name: apache-devlake-ui
            port:
              name: ui
        path: /devlake(/|$)(.*)
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - dev.myhost.io
    secretName: wildcard-tls
```
