### ISSUE TITLE
[Bug][Bitbucket_Server] After moving to v1.0.0-beta4 gitextractor server certificate verification failed. CAfile: none CRLfile

### ISSUE THREAD

**Issue by Capone1983** [apache/devlake#7329]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

After move from beta3 - beta4 the gitextractor has an error now when trying to clone the repo. 

server certificate verification failed. CAfile: none CRLfile: none caused by: exit status 128

I have added the self-signed certs to the image for both beta3 and beta4. 

Works for beta3 but not beta4

### What do you expect to happen

The repo should be cloned. 

### How to reproduce

Connect to bitbucket server and run the pipeline. 

### Version

v1.0.0-beta4

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
Thanks for reporting the problem, will look into it ASAP

**Comment by klesh** [comment]
Hi, I tried to reproduce the problem using docker-compose and gitlab with a self-signed certificate, It worked just fine...

Here is how I set it up

docker-compose.yml for gitlab server
```
version: '3.6'
services:
  web:
    container_name: gitlab
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    hostname: 'gitlab.local'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.local:32443'
        # Add any other gitlab.rb configuration here, each on its own line
        gitlab_rails['gitlab_shell_ssh_port'] = 3222
        letsencrypt['enable'] = false
    ports:
      - '3280:80'
      - '32443:32443'
      - '3222:22'
    volumes:
      - '~/docker/gitlabce/config:/etc/gitlab'
      - '~/docker/gitlabce/logs:/var/log/gitlab'
      - '~/docker/gitlabce/data:/var/opt/gitlab'
      - './cert/gitlab.key:/etc/gitlab/ssl/gitlab.local.key'
      - './cert/gitlab.crt:/etc/gitlab/ssl/gitlab.local.crt'
    shm_size: '256m'
    networks:
      - gitlabce

networks:
  gitlabce:
    driver: bridge
```

docker-compose.yml for `devlake`
```
  devlake:
    image: apache/devlake:v1.0.0-beta4
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - devlake-log:/app/logs
      - /path/to/gitlabce/cert/ca/rootCA.crt:/usr/local/share/ca-certificates/rootCA.crt
    command: [ "sh", "-c", "update-ca-certificates; lake" ]
    env_file:
      - ./.env
    environment:
      LOGGING_DIR: /app/logs
      TZ: UTC
    depends_on:
      - mysql
    networks:
      - gitlabce_gitlabce
      - devlake
```
