### ISSUE TITLE
[Question][external Grafana] won't create dora dashboard.

### ISSUE THREAD

**Issue by da-head0** [apache/devlake#8013]
## Question
Hello. I'm trying to use external grafana on helm install, but after pipeline finished, dashboard won't showing in my external grafana.

```
  # dependency chart values
  grafana:
    enabled: false
    #if grafana enabled is false, then external url should be provided
    external:
      url: "https://grafana.dev.company.io"
    image:
      repository: devlake.docker.scarf.sh/apache/devlake-dashboard
      tag: v1.0.1-beta6
    deploymentStrategy:
      type: Recreate
    adminPassword: "password" -> wich is correct admin password
    grafana.ini:
      server:
        serve_from_subpath: "true"
        root_url: "%(protocol)s://%(domain)s/grafana"
    #the secret name should be as same as .Values.option.connectionSecretName
    envFromSecrets:
      - name: "devlake-mysql-auth"
    #keep grafana timezone same as other pods, which is set by .Values.commonEnvs.TZ
    env:
      TZ: "UTC"
    persistence:
      enabled: true
      size: 4Gi
    ingressServiceName: ""
    ingressServicePort: ""
```

## Screenshots
If applicable, add screenshots to help explain.
<img width="1596" alt="image" src="https://github.com/user-attachments/assets/8f0db5f1-eb6d-4ea3-9a1e-a44eae82b2eb">

## Additional context
the loadbalancer connected to external grafana only accepts my office VPN and VPC nat IP, which I think devlake use(VPC NAT IP).
or should I add private IP CIDR from VPC?
